import type { Metadata } from "next";
import { Poppins, Beth_Ellen } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import "@fortawesome/fontawesome-free/css/all.min.css"

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight:["100","200","300","400","500","600"]
})
const beth_ellen = Beth_Ellen({
  variable: "--font-beth_ellen",
  subsets: ["latin"],
  weight:"400"
})

export const metadata: Metadata = {
  title: "Letícia Esteticista",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${poppins.variable} ${beth_ellen.variable}`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
